### PR TITLE
Create la-la.lang

### PR DESCRIPTION
**Pull request by michaeljcoffey**
Creating Latin localization (Lingua Latinae bona est!)  We want ancient Romans, the Pope, and students of Latin to have fun with Mystcraft, right?  Corrections and feedback welcome.

### CODE REVIEW

**Comment by HellFirePvP** [comment]
This. is. amazing.

However i don't actually know if you can change the minecraft client language to latin?

**Comment by michaeljcoffey** [comment]
You can.  When you start a game you can punch a tree to get some _Lignum Querceum_, craft a _Mensa Opa_ so you have the crafting space to make the tools to mine _saxa_ and _carbo_ and, if you're lucky, you quickly find a little _aes ferri_ so you can improve your tools.  :)

**Comment by IndigoAvemour** [comment]
I love this! Great work, I'd love to see Mystcraft in Latin.

**Comment by heldplayer** [comment]
I don't speak Latin so can't verify these translations, however I'm curious why you decided to remove the accents in your latest commit. Vanilla Latin translation has them as well so I would say they're appropriate here as well.

**Comment by HellFirePvP** [comment]
Well... i remember some parts of latin from school eventhough it's been a while. It looks at least somewhat close to what it should be. So i'd say it's fairly accurate in close to all cases as much as i can tell though.

**Comment by michaeljcoffey** [comment]
@heldplayer -- The Romans didn't use the macrons on their letters; the markings are more to help learners differentiate between values on different vowels.  A bit of trivia, malum (short a) means evil, while mālum (long a) means apple, and that's why we think the fruit in the Garden of Eden is an apple...really, the Latin Bible says it's a fruit of the knowledge of good and _malum,_ but not that it's specifically a mālum. :) 

The vanilla Latin translation only has a few macrons, and not ones that make grammatical difference.  Most long/short differences don't impact meaning, however, and context can usually make up the difference.  There are actually several bits of the vanilla translation I'm not satisfied with.  

For example, "door" is _ianua_ but that's usually (as far as I can tell) used specifically for a double doorway at the front of a house instead of the more general _ostium._  Or nether wart is translated with _verruca_ which means the skin growth rather than the meaning of "wort," Middle English for "plant" (as in "St. John's wort" or "mugwort").  Since nether wort is clearly a plant and not a skin growth, _verruca_ isn't a particularly good choice.   Finally, single/multi player is translated as "Ludus Unius" and "Ludus Multorum" which is fine except that "Ludus" means a game, whereas "Lusor" means a player of a game.  Game-of-One vs. Game-of-Many-Men.  I'd have done that differently.

Going briefly one step further off the topic of macron marks, but I chose to use _ater_ (dull black) rather than _niger_ (shining/glossy black) because ater is the etymological root of ink: _atramentum_ (lit. "instrument of blackness").  It's a choice that might be less accurate (_niger_ is both more common and used in vanilla MC), but it seemed more satisfying for Mystcraft.

**Comment by heldplayer** [comment]
Interesting to know. Thank you for explaining! :)

**Comment by gootube2000** [comment]
@michaeljcoffey If you'd like, you could suggest some changes to the vanilla translation over on [https://crowdin.com/project/minecraft/la-LA](https://crowdin.com/project/minecraft/la-LA)
The current translations aren't set in stone and still need a bit of revision, so you're welcome to fix any mistakes you find.

**Comment by HellFirePvP** [comment]
Would you please adjust the symbol names on your language file to the new lowercased symbol language file keys? Thank you o/

For reference: https://github.com/XCompWiz/Mystcraft-Issues/commit/9645e1b27d56c73b7e5c049161666b20748df4be

**Comment by XCompWiz** [comment]
@michaeljcoffey as Hell pointed out, the localizations changed. Sorry for the trouble, but would you be willing to update this to match? I'd love to roll it in. :D

**Comment by michaeljcoffey** [comment]
I believe that's all that was needed.  Let me know if I've missed something.  I'm still teaching summer term, but my schedule's a lot less intense than last quarter.  :)

**Pull request merged**
