### PR TITLE
Update nl_NL.lang

### PR DESCRIPTION
**Pull request by TimoMeijer**
I've updated the dutch translation to remove some grammatical errors and fell less clunky in general.

Please comment with any suggestions, and I'll update the translations. Please comment with even the most minor details, if you believe it'll improve the translations.

### CODE REVIEW

**Comment by Maxiebyte** [comment]
This translation is good for me.
:+1:

**Comment by TimoMeijer** [comment]
@XCompWiz, I believe this pull request is ready for merging, as I understand it, these translations have the support of @Maxiebyte, @Devocity, @dries007 & @heldplayer, except for some minor points, of which any proposed alternative could be used, but any of them are better than the current translations.

As a clarification to the comments of @Maxiebyte, which I communicated with him personally by email, his comments were in response to on an older version of the translations, which have since already been changed/fixed, and he agrees with the latest version.

**Comment by XCompWiz** [comment]
This merge seems to have gotten derailed somehow.
Please update it to the current HEAD and flatten your commits. :)

**Comment by TimoMeijer** [comment]
@XCompWiz It should be fully fixed, rebased & flattened now, ready to be merged.

**Pull request merged**
